### PR TITLE
Use azurerm v0.3.0

### PR DESCRIPTION
**Pull request by lbnjma**
- Split `account_type` variable into two variables
- Add mandatory `os_profile_windows_config`

### CODE REVIEW

**Comment by dtzar** [comment]
Got these errors when trying to apply the example in the readme:
```
4 error(s) occurred:

* module.windowsservers.azurerm_virtual_machine.vm-windows-with-datadisk[1]: 1 error(s) occurred:

* azurerm_virtual_machine.vm-windows-with-datadisk.1: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed'
: Code="DiskServiceInternalError" Message="Internal error in disk manager."
* module.linuxservers.azurerm_virtual_machine.vm-linux-with-datadisk[1]: 1 error(s) occurred:

* azurerm_virtual_machine.vm-linux-with-datadisk.1: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed':
Code="DiskServiceInternalError" Message="Internal error in disk manager."
* module.linuxservers.azurerm_virtual_machine.vm-linux-with-datadisk[0]: 1 error(s) occurred:

* azurerm_virtual_machine.vm-linux-with-datadisk.0: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed':
Code="DiskServiceInternalError" Message="Internal error in disk manager."
* module.windowsservers.azurerm_virtual_machine.vm-windows-with-datadisk[0]: 1 error(s) occurred:

* azurerm_virtual_machine.vm-windows-with-datadisk.0: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed'
: Code="DiskServiceInternalError" Message="Internal error in disk manager."
```

**Comment by dtzar** [comment]
The advanced one

**Comment by lbnjma** [comment]
Hi !

I removed the "format" syntax used in datadisk modules.
I don't have subscription to test now, can you tell me if it's ok ?

Regards,
Jérémy.

**Comment by dtzar** [comment]
This looks good, but I'm now hitting this: https://github.com/Azure/terraform-azurerm-network/issues/4

**Comment by dtzar** [comment]
Upstream DNS is fixed.  For reference, I noticed when apply the advanced example I sometimes get:
```
Error: Error applying plan:

1 error(s) occurred:

* module.windowsservers.output.public_ip_address: Resource 'azurerm_public_ip.vm' does not have attribute 'ip_address' for variable 'azurerm_public_ip.vm.*.ip_address'
```
But do a `terraform apply` again and works as expected.  Likely just a timing issue.

**Pull request merged**
