### PR TITLE
Fix broken ip_configuration when azurerm_public_ip is null

### PR DESCRIPTION
**Pull request by Amos-85**
## Problem
The error below appear when `length(azurerm_public_ip.vm[*].id) = 0`
```
╷
│ Error: parsing Azure ID: parse "": empty url
│ 
│   with module.vms["aiola"].azurerm_network_interface.vm[0],
│   on .terraform/modules/vms/main.tf line 446, in resource "azurerm_network_interface" "vm":
│  446:     public_ip_address_id = length(azurerm_public_ip.vm[*].id) > 0 ? element(concat(azurerm_public_ip.vm[*].id, tolist([
│  447:       ""
│  448:     ])), count.index) : ""
│ 
╵

```

## Describe your changes

* Change `azurerm_public_ip` to null instead of empty string.

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [x] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

### CODE REVIEW

**Comment by Amos-85** [comment]
@microsoft-github-policy-service agree

**Comment by Amos-85** [comment]
Hi @lonegunmanb,
Can you please advice / check this PR ?

**Review by lonegunmanb — APPROVED** [review]
Thanks @Amos-85 for opening this pr, LGTM! 🚀

**Comment by Amos-85** [comment]
Thanks @lonegunmanb for you attention.
Do you tend to release hotfix versions in such used cases ?
The module is not functional when `azurerm_public_ip` is not in use.

**Comment by lonegunmanb** [comment]
> Thanks @lonegunmanb for you attention. Do you tend to release hotfix versions in such used cases ? The module is not functional when `azurerm_public_ip` is not in use.

Thanks for your notification @Amos-85, you're right, I'll release the hotfix right way.

**Pull request merged**
