### PR TITLE
Use name template variables to customize the name of each resource

### PR DESCRIPTION
**Pull request by DatsloJRel**
## Describe your changes
Added the ability to optionally name resources using variables for name templates.  This allows each resource created to have a custom name.

## Checklist before requesting a review
- [X] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [X] I have executed pre-commit on my machine
- [X] I have passed pr-check on my machine

### CODE REVIEW

**Review by lonegunmanb — CHANGES_REQUESTED** [review]
Thanks @DatsloJRel for opening this pr. I like this idea, but a simple `var.group_by_vm_instance` only provides one alternative naming pattern, I'm thinking of a more flexible way.

My thought is providing several naming template variable to render resource's name, so we can customize the template. e.g.:

```hcl
var.group_by_vm_instance ? join("-", [var.vm_hostname, host_number, "datadisk", data_disk_number]) : join("-", [var.vm_hostname, "datadisk", host_number, data_disk_number])
```

This expression implied two different templates: `${vm_hostname}-${host_number}-datadisk-${data_disk_number}` && `${vm_hostname}-datadisk-${host_number}-${data_disk_number}`. We can also assigned a different template, like `${vm_hostname}-${host_number}-dd-${data_disk_number}`.

The problem is, Terraform is lacking of `templatestring` function like [`templatefile`](https://developer.hashicorp.com/terraform/language/functions/templatefile) do. So a possible way is to use multiple `replace`, like this [comment](https://github.com/hashicorp/terraform/issues/26838#issuecomment-840022506) suggested:

```hcl
replace(replace(replace(var.data_disk_name_template, "${vm_hostname}", var.vm_hostname), "${host_number}", hostnumber), "${data_disk_number}", data_disk_number)
```

Meanwhile the default value for this `var.data_disk_name_template` is `${vm_hostname}-datadisk-${host_number}-${data_disk_number}`. You can customize your template as you like.

**Comment by DatsloJRel** [comment]
@lonegunmanb Thanks for the suggestion of using `replace(replace(replace(...)))` as that is a very nice way of making fully custom resource names.  I have updated the code with these changes.  Please let me know if this looks acceptable to you, or if you would like some other change associated with it.

In total, there are now 10 new variables for the name templates:
```
  availability_set_name_template       = "$${vm_hostname}-avset"
  data_disk_name_template              = "$${vm_hostname}-datadisk-$${host_number}-$${data_disk_number}"
  extra_disk_name_template             = "$${vm_hostname}-extradisk-$${host_number}-$${extra_disk_name}"
  network_interface_name_template      = "$${vm_hostname}-nic-$${host_number}"
  network_security_group_name_template = "$${vm_hostname}-nsg"
  public_ip_name_template              = "$${vm_hostname}-pip-$${ip_number}"
  vm_linux_name_template               = "$${vm_hostname}-vmLinux-$${host_number}"
  vm_linux_os_disk_name_template       = "osdisk-$${vm_hostname}-$${host_number}"
  vm_windows_name_template             = "$${vm_hostname}-vmWindows-$${host_number}"
  vm_windows_os_disk_name_template     = "$${vm_hostname}-osdisk-$${host_number}"
```

It is unfortunate that `vm_linux_os_disk_name_template` and `vm_windows_os_disk_name_template` must be different by default, but that is what is existing in the terraform file.

**Comment by DatsloJRel** [comment]
@lonegunmanb If you would prefer to group the 10 `template_name` variables together, I had considered naming them with the format of `name_template_xxxx`, such as `name_template_data_disk` and `name_template_vm_linux`.  That way, all the name templates would be together in the `variables.tf` file.  I don't know the specific rules for naming, so I will agree with what you think is best.

**Comment by lonegunmanb** [comment]
> @lonegunmanb If you would prefer to group the 10 `template_name` variables together, I had considered naming them with the format of `name_template_xxxx`, such as `name_template_data_disk` and `name_template_vm_linux`. That way, all the name templates would be together in the `variables.tf` file. I don't know the specific rules for naming, so I will agree with what you think is best.

@DatsloJRel Wow thanks for your careful consideration! I like the `name_template_xxx` idea, but I have one question: why you choose `$${xxx}` as template variable instead of using `${xxx}`? In terraform's template function, `$${xxx}` means escape symbol, which the final string would be `${xxx}`.

**Comment by DatsloJRel** [comment]
@lonegunmanb There is no rule that we need to use `$${xxxx}` as the replacement identifier.  It could be any string, like `<xxxx>` or `{xxxx}` or `(xxxx)`.   We just need to use some format in the `variables.tf` file and in each `replace(....)` function.  The [comment](https://github.com/hashicorp/terraform/issues/26838#issuecomment-840022506) that you referenced uses the `$${xxx}` format, so that is what I used.

**Comment by DatsloJRel** [comment]
@lonegunmanb The PR has been updated for `name_template_xxxx` now.  Let me know if there is anything else.

**Review by lonegunmanb — APPROVED** [review]
Thanks @DatsloJRel, LGTM! 🚀

**Pull request merged**
